"""Executive PDF report generator using ReportLab."""

from pathlib import Path

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

from sim_engine.analytics import Analytics


def generate_pdf_report(run_path: str, output_pdf_path: str) -> bool:
    """Generate a professional PDF executive report.

    Args:
        run_path: Path to the simulation run directory.
        output_pdf_path: Path where the output PDF should be saved.

    Returns:
        True if successful, False otherwise.
    """
    try:
        run_dir = Path(run_path)
        output_path = Path(output_pdf_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)

        # Load analytics
        analytics = Analytics(str(run_dir))
        if not analytics.load_data():
            print(f"❌ Error: Failed to load analytics data from {run_dir}")
            return False

        summary = analytics.compute_summary()
        segments = analytics.compute_segment_analysis()
        revenue = analytics.compute_revenue_estimate()
        churn_fc = analytics.get_churn_forecast()

        # Setup document
        doc = SimpleDocTemplate(
            str(output_path),
            pagesize=letter,
            rightMargin=0.75 * inch,
            leftMargin=0.75 * inch,
            topMargin=0.75 * inch,
            bottomMargin=0.75 * inch,
        )

        # Setup styles
        styles = getSampleStyleSheet()

        # Custom palette
        primary_color = colors.HexColor("#1e293b")  # Slate 800
        secondary_color = colors.HexColor("#3b82f6")  # Blue 500
        text_color = colors.HexColor("#334155")  # Slate 700
        accent_color = colors.HexColor("#ef4444")  # Red 500
        bg_light = colors.HexColor("#f8fafc")  # Slate 50

        title_style = ParagraphStyle(
            'DocTitle',
            parent=styles['Heading1'],
            fontName='Helvetica-Bold',
            fontSize=24,
            leading=28,
            textColor=primary_color,
            spaceAfter=6,
        )

        subtitle_style = ParagraphStyle(
            'DocSubtitle',
            parent=styles['Normal'],
            fontName='Helvetica',
            fontSize=12,
            textColor=secondary_color,
            spaceAfter=20,
        )

        h1_style = ParagraphStyle(
            'SectionHeader',
            parent=styles['Heading2'],
            fontName='Helvetica-Bold',
            fontSize=16,
            leading=20,
            textColor=primary_color,
            spaceBefore=14,
            spaceAfter=10,
            keepWithNext=True,
        )

        body_style = ParagraphStyle(
            'Body',
            parent=styles['Normal'],
            fontName='Helvetica',
            fontSize=10,
            leading=14,
            textColor=text_color,
            spaceAfter=8,
        )

        bold_body_style = ParagraphStyle(
            'BoldBody',
            parent=body_style,
            fontName='Helvetica-Bold',
        )

        table_header_style = ParagraphStyle(
            'TableHeader',
            parent=styles['Normal'],
            fontName='Helvetica-Bold',
            fontSize=9,
            leading=11,
            textColor=colors.white,
        )

        table_cell_style = ParagraphStyle(
            'TableCell',
            parent=styles['Normal'],
            fontName='Helvetica',
            fontSize=9,
            leading=11,
            textColor=text_color,
        )

        story = []

        # --- TITLE BLOCK ---
        story.append(Paragraph("Synthesized Market Simulation Engine", title_style))
        story.append(Paragraph(f"Executive Simulation Report &bull; Run ID: {run_dir.name}", subtitle_style))
        story.append(Spacer(1, 10))

        # --- EXECUTIVE SUMMARY ---
        story.append(Paragraph("Executive Summary", h1_style))
        exec_text = (
            "This report delivers high-fidelity business insights generated by the Synthesized Market "
            "Simulation Engine. By modeling multi-agent behaviors, competitive actions, and consumer segment "
            "dynamics, the engine projects transactional volume, behavioral drift, and customer retention metrics "
            "over multiple rounds. The simulated interactions demonstrate how specific product features, pricing changes, "
            "and market shocks impact business KPIs and revenue streams."
        )
        story.append(Paragraph(exec_text, body_style))
        story.append(Spacer(1, 12))

        # --- CORE KPIs TABLE ---
        story.append(Paragraph("Key Performance Indicators (KPIs)", h1_style))

        kpi_data = [
            [Paragraph("Metric", table_header_style), Paragraph("Value / Projection", table_header_style), Paragraph("Analysis & Context", table_header_style)],
            [
                Paragraph("Total Sim Transactions", table_cell_style),
                Paragraph(str(summary.get("total_transactions", 0)), table_cell_style),
                Paragraph("Aggregate volume of consumer and competitor actions simulated.", table_cell_style),
            ],
            [
                Paragraph("Gross Revenue Estimate", table_cell_style),
                Paragraph(f"${revenue.get('gross_revenue_estimate', 0.0):,.2f}", table_cell_style),
                Paragraph("Direct positive purchase revenue captured across all rounds.", table_cell_style),
            ],
            [
                Paragraph("Projected Churn Rate", table_cell_style),
                Paragraph(f"{churn_fc.get('projected_churn_rate', 0.0) * 100:.1f}%", table_cell_style),
                Paragraph(f"Trend: <b>{churn_fc.get('trend', 'stable').upper()}</b>. Indicates expected long-term risk.", table_cell_style),
            ],
            [
                Paragraph("Estimated Churn Loss", table_cell_style),
                Paragraph(f"${revenue.get('churn_loss_estimate', 0.0):,.2f}", table_cell_style),
                Paragraph("Negative revenue impact due to customers shifting or churning.", table_cell_style),
            ],
            [
                Paragraph("Net Simulated Revenue", table_cell_style),
                Paragraph(f"${revenue.get('net_revenue_estimate', 0.0):,.2f}", table_cell_style),
                Paragraph("Estimated true value generated, adjusting for customer attrition.", table_cell_style),
            ],
        ]

        kpi_table = Table(kpi_data, colWidths=[2.0 * inch, 1.8 * inch, 3.2 * inch])
        kpi_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), primary_color),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('TOPPADDING', (0, 0), (-1, -1), 6),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
            ('LEFTPADDING', (0, 0), (-1, -1), 8),
            ('RIGHTPADDING', (0, 0), (-1, -1), 8),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, bg_light]),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
        ]))
        story.append(kpi_table)
        story.append(Spacer(1, 15))

        # --- ROUND-BY-ROUND METRICS ---
        story.append(Paragraph("Round-by-Round Performance Metrics", h1_style))

        round_headers = [
            Paragraph("Round", table_header_style),
            Paragraph("Active Consumers", table_header_style),
            Paragraph("Purchases", table_header_style),
            Paragraph("Holds", table_header_style),
            Paragraph("Switches", table_header_style),
            Paragraph("Churns", table_header_style),
        ]

        round_rows = [round_headers]
        for r_data in summary.get("by_round", []):
            round_rows.append([
                Paragraph(str(r_data.get("round")), table_cell_style),
                Paragraph(str(r_data.get("total")), table_cell_style),
                Paragraph(str(r_data.get("purchases")), table_cell_style),
                Paragraph(str(r_data.get("holds")), table_cell_style),
                Paragraph(str(r_data.get("switches")), table_cell_style),
                Paragraph(str(r_data.get("churns")), table_cell_style),
            ])

        if len(round_rows) == 1:
            # Placeholder if no round metrics
            round_rows.append([Paragraph("No round metrics available.", table_cell_style)] + [Paragraph("-", table_cell_style)] * 5)

        round_table = Table(round_rows, colWidths=[1.0 * inch, 1.2 * inch, 1.2 * inch, 1.2 * inch, 1.2 * inch, 1.2 * inch])
        round_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), secondary_color),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('TOPPADDING', (0, 0), (-1, -1), 5),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
            ('LEFTPADDING', (0, 0), (-1, -1), 6),
            ('RIGHTPADDING', (0, 0), (-1, -1), 6),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, bg_light]),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
        ]))
        story.append(round_table)
        story.append(Spacer(1, 15))

        # --- SEGMENT-LEVEL BREAKDOWN ---
        story.append(Paragraph("Segment-level Breakdown & Risk", h1_style))

        segment_headers = [
            Paragraph("Consumer Segment", table_header_style),
            Paragraph("Persona Count", table_header_style),
            Paragraph("Simulated Purchase Rate", table_header_style),
            Paragraph("Projected Churn Rate", table_header_style),
        ]

        segment_rows = [segment_headers]
        for s_data in segments.get("segments", []):
            segment_rows.append([
                Paragraph(s_data.get("segment", "unknown").upper(), table_cell_style),
                Paragraph(str(s_data.get("count", 0)), table_cell_style),
                Paragraph(f"{s_data.get('purchase_rate', 0.0) * 100:.1f}%", table_cell_style),
                Paragraph(f"{s_data.get('churn_rate', 0.0) * 100:.1f}%", table_cell_style),
            ])

        if len(segment_rows) == 1:
            segment_rows.append([Paragraph("No segment metrics available.", table_cell_style)] + [Paragraph("-", table_cell_style)] * 3)

        segment_table = Table(segment_rows, colWidths=[2.2 * inch, 1.4 * inch, 1.7 * inch, 1.7 * inch])
        segment_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), primary_color),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('TOPPADDING', (0, 0), (-1, -1), 5),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
            ('LEFTPADDING', (0, 0), (-1, -1), 6),
            ('RIGHTPADDING', (0, 0), (-1, -1), 6),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, bg_light]),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
        ]))
        story.append(segment_table)
        story.append(Spacer(1, 15))

        # --- STRATEGIC RECOMMENDATIONS ---
        story.append(Paragraph("Strategic Recommendations", h1_style))

        # Dynamic suggestions based on churn
        rec_title_1 = "1. Mitigate Customer Churn"
        rec_desc_1 = (
            f"The simulation indicates a projected churn rate of {churn_fc.get('projected_churn_rate', 0.0) * 100:.1f}%. "
            "Target highly sensitive consumer segments with loyalty initiatives, promo bundles, or customized price-matching "
            "to prevent switching behavior."
        )
        if churn_fc.get("trend") == "increasing":
            rec_desc_1 += " Immediate action is recommended since the churn risk shows an INCREASING trend."

        rec_title_2 = "2. Competitor Counter-Moves"
        rec_desc_2 = (
            "Monitor challenger competitive personas closely. When competitors discount pricing or increase feature "
            "acceleration, proactively upgrade core features and optimize marketing messaging to assert product positioning."
        )

        rec_title_3 = "3. Resource Tuning & Modeling"
        rec_desc_3 = (
            "To capture deeper multi-agent nuances, scale up the simulation using a 'balanced' or 'high' resource profile "
            "backed by Ollama or OpenAI inference, expanding memory retrieval thresholds to capture comprehensive context."
        )

        story.append(Paragraph(f"<b>{rec_title_1}</b>", bold_body_style))
        story.append(Paragraph(rec_desc_1, body_style))
        story.append(Spacer(1, 4))

        story.append(Paragraph(f"<b>{rec_title_2}</b>", bold_body_style))
        story.append(Paragraph(rec_desc_2, body_style))
        story.append(Spacer(1, 4))

        story.append(Paragraph(f"<b>{rec_title_3}</b>", bold_body_style))
        story.append(Paragraph(rec_desc_3, body_style))

        # Build PDF
        doc.build(story)
        print(f"✓ Executive PDF report successfully generated at {output_path}")
        return True

    except Exception as e:
        print(f"❌ Error generating PDF: {str(e)}")
        import traceback
        traceback.print_exc()
        return False
